[colors.normal]
black = "#1c1c1c"
blue = "#5f87af"
cyan = "#5f8787"
green = "#5f875f"
magenta = "#875f87"
red = "#af5f5f"
white = "#e5e5e5"
yellow = "#87875f"

[colors.primary]
background = "#0e0e0e"
foreground = "#e5e5e5"

[cursor]
style = "Block"

[env]
WINIT_UNIX_BACKEND = "wayland"

[font]
size = 12

[window]
opacity = 0.95

[window.padding]
x = 6
y = 6

[terminal]
shell = "/usr/bin/fish"
